import Head from 'next/head';
import { Box, Typography } from '@mui/material';
import { indexStyle } from '@/features/styles/IndexStyles';

export default function Home() {
  return (
    <>
      <Head>
        <title>Plant Diary</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={indexStyle.backgroundStyle}>
        <Box sx={indexStyle.yellowBox}></Box>
        <Box sx={indexStyle.verticalLeft}></Box>
        <Box sx={indexStyle.verticalRight}></Box>
        <Box sx={indexStyle.titleBackground}>
          <Box sx={indexStyle.desc}>
            <Typography sx={indexStyle.text} variant="h2">
              Days of Planty
            </Typography>
            <Typography sx={indexStyle.text} variant="h5">
              Keep track of your plants
            </Typography>
            <Typography sx={indexStyle.text} variant="h5">
              Next.js, Typescript
            </Typography>
            <Typography sx={indexStyle.text} variant="h6">
              By.Haeju
            </Typography>
          </Box>
        </Box>
      </Box>
    </>
  );
}
