import Head from 'next/head';
import { Inter } from '@next/font/google';
import IndexLayout from '@/layout';
import { ReactElement } from 'react';

export default function Home() {
  return (
    <>
      <Head>
        <title>Plant Diary</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}

Home.getLayout = function getLayout(page: ReactElement) {
  return <IndexLayout>{page}</IndexLayout>;
};
